spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:hsqldb:mem:voting
    username: sa
    password:

  cache:
    cache-names: users, restaurants, dishes
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging:
  level:
    root: WARN
    com.github.lembek.RestaurantVoiting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
